import type { CardCatalogV2 } from "./schema";

// Author-controlled Court Record case copy (generated once, then edited by hand where desired).
export const COURT_CASE_BY_CARD_ID: Record<string, string> = {
  "ape_phalanx": "Ape Phalanx locks the front row with pure collective stubbornness and makes every clean attack feel like arguing with a crowd that already printed the screenshots.",
  "arb_tactician": "Arb Tactician lives in the spread, pressures both rows, and makes every small misprice feel like a personal invitation.",
  "auction_breaker": "Auction Breaker opens with fireworks and turns the first moments of order into a controlled market incident.",
  "auction_clerk": "Auction Clerk controls opening bell mood with clipboard calm and enough timing edge to make neutrality look suspicious.",
  "audit_committee": "Audit Committee arrives as governance paperwork and somehow turns a quiet board state into a hearing with minutes, motions, and consequences.",
  "audit_raider": "Audit Raider hits at dawn like a surprise inspection with legs and leaves the board looking like half the books just got seized.",
  "bagholder_tank": "Bagholder Tank carries losses like plate armor and stands in front so long that even good trades start to look emotionally overleveraged.",
  "balance_sheet_ogre": "Balance Sheet Ogre entered the record as a Wallstreet wall of audited muscle that plants in the front row and dares the room to discover just how expensive \"thick assets\" can feel.",
  "banana_fund": "Banana Fund enters as snack-grade support and somehow keeps the yolo engine fueled like nutrition was always the missing combo piece.",
  "banner_holder": "Banner Holder plants a cheap frontline taunt with such loud conviction that the opponent spends a whole turn fighting a slogan instead of the board.",
  "blue_chip_raider": "Blue Chip Raider keeps getting named in complaints because it hits like premium paper with street confidence and somehow still looks \"responsible\" while pressuring both lanes.",
  "boardroom_negotiator": "Boardroom Negotiator smiles over costly water, invoices the conversation, and leaves the hearing convinced that diplomacy was just another way to win tempo from the back row.",
  "bonus_chaser": "Bonus Chaser treats every exchange like quarter-end comp review and swings harder the moment the room starts acting like restraint is a virtue.",
  "book_depth_guard": "Book Depth Guard stands like thick depth made flesh and forces the lane to trade through a wall of patient liquidity.",
  "borrow_desk_clerk": "Borrow Desk Clerk finds lendable shadows with clerical calm and keeps the short engine running like scarcity was just another office supply.",
  "borrow_rate_whisperer": "Borrow Rate Whisperer talks APR like bedtime horror and makes the cost of being wrong sound strangely precise.",
  "borrowed_shield": "Borrowed Shield arrives under the banner of prudence and then reveals the plan was always \"borrow now, explain never.\"",
  "bribe_courier": "Bribe Courier moves Judge-blue influence with courier-level efficiency and the kind of smile that makes every envelope look guilty.",
  "bullhorn_raider": "Bullhorn Raider delivers alpha at maximum volume and turns every swing into a public announcement nobody can ignore.",
  "buyback_authorization": "Buyback Authorization was filed as shareholder care, but the court record notes it mostly retires patience, shrinks breathing room, and makes the tape look cleaner than the motive.",
  "capital_adequacy_titan": "Capital Adequacy Titan stands in front like a regulatory fortress with cufflinks, absorbing the mess so efficiently it starts to look like policy.",
  "cease_desist_guard": "Cease & Desist Guard patrols with a giant red stamp and the exact energy of a frontline warning nobody wants to test twice.",
  "circuit_breaker_act": "Circuit Breaker Act slows the chaos by force of statute and reminds both sides that momentum still answers to paperwork sometimes.",
  "circuit_pause": "Circuit Pause is a pocket halt that buys one sober breath before the chaos remembers where it left off.",
  "civic_auditor": "Civic Auditor applies backline audit pressure with public-duty posture and the kind of notes that become sanctions later.",
  "class_action_counsel": "Class Action Counsel loves large groups and fees, which is unfortunate because both keep appearing wherever the fight gets crowded.",
  "cleanup_cart": "Cleanup Cart is a rolling obstacle of pure inconvenience that nobody respects until it steals exactly one clean line.",
  "cleanup_emergency_cone": "Emergency Cone does nothing flashy except exist in the wrong place at the right time, which is apparently enough to ruin tempo.",
  "cleanup_rubble": "Rubble sits there like an afterthought and still forces better players to spend a turn pretending debris is a tactical decision.",
  "cleanup_suit_rack": "Suit Rack clogs space with courtroom fashion energy and proves that even a hanger can become a board problem.",
  "cleanup_wet_floor_sign": "Wet Floor Sign blocks progress with public-safety authority and the humiliating possibility that the warning was correct.",
  "clearing_knight": "Clearing Knight looks like a frontline formality until the lance reaches past traffic and reminds the back row that settlement risk can arrive in armor.",
  "clearing_router": "Clearing Router routes risk to someone else so cleanly that the losing side needs a diagram to explain what happened.",
  "collateral_bunker": "Collateral Bunker is fortified by everybody else's collateral and sits in lane like moral hazard learned to tank.",
  "community_steward": "Community Steward keeps the retail line together by making chaos look organized long enough for the next push to land.",
  "compliance_bruiser": "Compliance Bruiser has no alpha and no patience, only rules applied with enough force to count as frontline persuasion.",
  "compliance_clerk": "Compliance Clerk keeps allies patched, cleaned, and court-ready from the back row while carrying enough green-lane paperwork to count as artillery.",
  "compliance_doorman_ws": "Compliance Doorman checks badges, blocks the lane, and soaks damage with such polished manners that opponents realize too late they were arguing with a vault door.",
  "compliance_hotline": "Compliance Hotline turns anonymous tips into instant panic and proves that a ringing phone can be a combat action.",
  "compliance_liaison_ws": "Compliance Liaison says \"happy to help\" from the back row while quietly delaying your plan by exactly one turn too many and calling it process.",
  "compliance_scapegoat": "Compliance Scapegoat wears a legal-looking tie, eats the first hit, and gets sacrificed with enough ceremony to count as process.",
  "consent_decree_agent": "Consent Decree Agent settles with a scary smile and makes cooperation feel like a sentence with better formatting.",
  "court_liaison": "Court Liaison speaks neutral in both Judge dialects and makes cross-faction politics look like a practical utility tool.",
  "court_observer": "Court Observer takes notes, takes souls, and somehow turns passive attendance into a tactical liability for the other side.",
  "covenant_flex": "Covenant Flex enters as a harmless clause tweak, then bends the whole agreement around one very expensive interpretation of the word \"maybe.\"",
  "credit_raider": "Credit Raider refinances your life total into a structured inconvenience and sends the bill before the term sheet finishes cooling.",
  "cross_venue_sync": "Cross Venue Sync links fragmented books and makes scattered pressure behave like one coordinated machine.",
  "crowd_shield": "Crowd Shield is a human wall of small lots that absorbs pressure one stubborn share at a time until the lane simply stops being convenient.",
  "dark_analyst": "Dark Analyst writes forty-page doom posts so convincing that even winning boards start checking for hidden liabilities.",
  "darkpool_accountant": "Darkpool Accountant reconciles invisible prints and somehow makes off-book activity sound like disciplined bookkeeping.",
  "darkpool_flashlight": "Darkpool Flashlight finds hidden prints and shines just enough truth to make someone else's lane unsafe.",
  "darkpool_hunter": "Darkpool Hunter lights up hidden liquidity and ruins the comfort of anyone trying to stay unseen.",
  "data_scraper": "Data Scraper combs public breadcrumbs into targeting value and acts like open-source snooping was a divine right of retail research.",
  "deal_desk_titan": "Deal Desk Titan carries M&A in a briefcase like it weighs nothing, then turns the front row into a live transaction the second combat starts.",
  "deal_paralegal": "Deal Paralegal arrives buried under nine hundred pages, yet somehow finds the exact footnote that keeps allies standing and opponents lost in review.",
  "dealbook_lancer": "Dealbook Lancer fights like page 417 was highlighted for blood, picking the soft target and citing precedent on the way through.",
  "debt_structurer": "Debt Structurer turns pain into tranches so elegantly that the court had to underline which part was finance and which part was violence.",
  "delta_keeper": "Delta Keeper hedges until it hurts and calls the pain a necessary cost of elegant exposure management.",
  "derivative_spear": "Derivative Spear is what happens when leverage gets a pointy end and somebody in Wallstreet decides risk transfer should also pierce the backline.",
  "diamond_barricade": "Diamond Barricade is built from conviction and screenshots, then placed in front like the court itself subpoenaed morale.",
  "diamond_chant_captain": "Diamond Chant Captain starts by taunting the room and ends by swinging harder once the crowd rhythm turns into momentum.",
  "diamond_hand_captain": "Diamond Hand Captain leads pushes like patience was a combat stat, anchoring the lane while the rest of the crowd catches up.",
  "diamond_hands_oath": "Diamond Hands Oath reads like a promise, plays like stubborn infrastructure, and keeps the board holding through chaos it probably should not survive.",
  "diamond_pikeman": "Diamond Pikeman pokes straight through FUD with retail certainty and leaves cleaner lines for the next hitter behind it.",
  "dip_buyer": "Dip Buyer treats every red candle like a limited-time invitation and turns panic on the tape into an opening bid.",
  "disclosure_dump": "Disclosure Dump floods the market with filings until the board starts drowning in truth-shaped paperwork.",
  "disclosure_sergeant": "Disclosure Sergeant delivers quarterly pain on schedule and treats reporting season like a combat doctrine.",
  "discord_moderator": "Discord Moderator bans bots, spawns morale, and somehow makes digital housekeeping feel like a combat buff.",
  "docket_enforcer": "Docket Enforcer slaps fines with a stapler and walks the lane like stationery was always a valid weapon class.",
  "doom_researcher": "Doom Researcher publishes a price target of zero with such commitment that the headline alone starts trading for damage.",
  "due_process_order": "Due Process Order fortifies a unit and trims probation with the maddening efficiency of a motion filed on time.",
  "earnings_guidance_spin": "Earnings Guidance Spin walks in as messaging support and leaves the chamber with reality adjusted to management's preferred quarter.",
  "exchange_clerk": "Exchange Clerk keeps the market barely legal with tired precision and the posture of someone who has seen every trick twice.",
  "execution_auditor": "Execution Auditor delivers best execution and best sarcasm, then grades the board like everyone else submitted late.",
  "fact_checker_ape": "Fact Checker Ape actually reads filings and fights with the terrifying confidence of someone carrying receipts.",
  "federal_receiver": "Federal Receiver confiscates tempo by standing there heavily and making ownership sound suddenly negotiable.",
  "fee_harvester": "Fee Harvester monetizes borrow pain with professional cheer and treats suffering like a recurring revenue stream.",
  "filing_archivist": "Filing Archivist buffs morale with binders and somehow makes administrative order feel like a combat steroid.",
  "filing_ram": "Filing Ram breaks through with Form 8-K energy and treats disclosure like a battering tool.",
  "filing_shield_deputy": "Filing Shield Deputy is budget taunt with clipboard courage, stepping in front like compliance was a contact sport.",
  "fine_schedule": "Fine Schedule looks like a menu and plays like a threat, itemizing exactly how expensive bad behavior can get.",
  "floor_chatter": "Floor Chatter spreads rumor-speed pressure so fast the board starts reacting before the evidence finishes loading.",
  "floor_mediator": "Floor Mediator claims to calm the room, but the record shows a frontline envoy who translates conflict into premium terms and keeps the Judge lane profitable.",
  "forensic_journalist": "Forensic Journalist prints receipts at dawn and turns rumor into evidence before breakfast clears the wire.",
  "forensic_raider": "Forensic Raider finds ghosts in ledgers and swings like each missing line item owes personal money.",
  "freeze_order_knight": "Freeze Order Knight rides in with assets frozen and feelings included, then locks the lane into procedural winter.",
  "ftd_collector": "FTD Collector never delivers on time but always shows up to demand payment, penalties, and one more concession.",
  "fud_negotiator": "FUD Negotiator gaslights politely enough to pass for diplomacy while your board quietly loses confidence.",
  "gamma_ape": "Gamma Ape runs on OTM call fumes and hits like the options chain personally dared it to overperform.",
  "gamma_sweeper": "Gamma Sweeper specializes in options pain and cleans up crowded positions with frighteningly practical reach.",
  "governance_warden": "Governance Warden runs committee-grade support from the back row, stacking order, cover, and procedural headaches until the whole desk feels board-approved.",
  "grey_pool_fixer": "Grey Pool Fixer brings neutral dirty work to the blue lane and acts like plausible deniability is a public service.",
  "guild_bailiff": "Guild Bailiff is an SEC shield in uniform form, taunting the front row with official confidence and no appeal window.",
  "halt_auction_warden": "Halt Auction Warden taunts first, reprices the whole argument after, and leaves the room wondering who authorized the pause.",
  "halt_marshall": "Halt Marshall is a trading stop on two legs that turns live aggression into a queue for permission.",
  "headline_scraper": "Headline Scraper harvests sentiment shifts straight from the noise and packages them into a surprisingly sharp utility hit.",
  "hearing_gladiator": "Hearing Gladiator cross-examines with steel and treats every exchange like testimony under pressure.",
  "hit_piece_sniper": "Hit Piece Sniper manages backline fear from a safe distance and files every shot as an urgent correction to sentiment.",
  "imbalance_reader": "Imbalance Reader watches open-close rituals like a priest of order flow and pounces when the tape starts confessing.",
  "injunction_captain": "Injunction Captain taunts the lane and feeds prosecutor pressure like courtroom control was a teamwide buff aura.",
  "insider_briefcase": "Insider Briefcase looks like a prop until it opens and somebody friendly suddenly swings like the memo came from upstairs.",
  "integrity_analyst": "Integrity Analyst counts red flags per minute and somehow keeps finding new integers for concern.",
  "investor_relations_chief": "Investor Relations Chief performs guidance magic in plain sight, soothing the board, feeding the story, and making every uncomfortable number sound temporary.",
  "ipo_ram": "IPO Ram hits the front line like listing-day euphoria with horns, paperwork, and no interest in waiting for the lockup talk.",
  "laser_pointer_ape": "Laser Pointer Ape calls the target for the whole subreddit and makes focus fire look like a community service.",
  "latency_lancer": "Latency Lancer shaves milliseconds and HP in the same motion, which is exactly the kind of efficiency people resent.",
  "latency_patch": "Latency Patch looks like a small technical fix until the buff lands and your best line suddenly belongs to the other side.",
  "legal_firewall": "Legal Firewall adds survivability with the cold confidence of protection clauses nobody read until it mattered.",
  "lender_last_resort": "Lender of Last Resort arrives with universal emergency money and the kind of terms everyone hates after saying yes.",
  "liquidity_bulkhead": "Liquidity Bulkhead stays put when spreads widen and turns market stress into a test of who can hit through structure.",
  "liquidity_duelist": "Liquidity Duelist fights 1v1 on a price ladder and makes every tick feel like a formal challenge.",
  "liquidity_provider": "Liquidity Provider is the plain universal cash button that never gets applause and always gets used.",
  "liquidity_window": "Liquidity Window opens exactly when insiders need an elegant exit and closes the moment anyone asks who priced the convenience.",
  "liquidity_window_global": "Global Liquidity Window offers temporary access to capital with immaculate timing and a faint smell of future regret.",
  "locate_alchemist": "Locate Alchemist turns maybe-locates into certainty and makes impossible inventory appear right before the short thesis needs oxygen.",
  "macro_commentator": "Macro Commentator is wrong loudly, daily, and somehow still influences the room by sheer broadcast stamina.",
  "maker_incentive": "Maker Incentive pays for tighter spreads and quietly convinces the board to behave like order was always profitable.",
  "market_arbiter": "Market Arbiter negotiates from range with marksman precision and makes Judge-green politics look like flow optimization.",
  "market_holiday": "Market Holiday calms everyone down just long enough for the next bad decision to queue up in peace.",
  "market_referee": "Market Referee blows the whistle on spoofing and then keeps blowing until the whole board starts behaving by accident.",
  "match_engine_rider": "Match Engine Rider clears queues violently and still acts like it merely improved throughput.",
  "media_handler": "Media Handler curates panic narratives with newsroom polish and drops them exactly where momentum is most fragile.",
  "media_smear": "Media Smear trims attack at random like a cheap headline haircut and leaves the target looking weaker than the tape remembers.",
  "meme_berserker": "Meme Berserker is a glass cannon with timeline energy, exploding into pressure before anyone remembers to respect the downside.",
  "meme_editor": "Meme Editor crops, captions, and buffs the right unit so efficiently it feels like propaganda with impeccable timing.",
  "merger_hunter": "Merger Hunter roams the board sniffing for synergies, then calls the takedown \"strategic fit\" once somebody else's position starts looking accretive.",
  "midpoint_raider": "Midpoint Raider steals pennies, wins wars, and leaves the ledger looking too clean for what just happened.",
  "naked_shorting": "Naked Shorting sells universal leverage in suspiciously convenient ratios and leaves debt, heat, and denial in equal measure.",
  "narrative_assassin": "Narrative Assassin kills momentum with one headline and then waits for the market to finish the job.",
  "options_gladiator": "Options Gladiator fights like every round expires at close and still finds a way to die ITM in spirit.",
  "options_grinder": "Options Grinder bleeds theta and opponents in the same motion, then calls the whole thing disciplined decay management.",
  "orderflow_scout": "Orderflow Scout is cheap tempo with sharp instincts, showing up early and making the next move easier than it should be.",
  "panic_knight": "Panic Knight wears fear like armor and marches forward as if dread itself were a premium defensive package.",
  "panic_seller_agent": "Panic Seller Agent spreads urgency professionally and makes orderly exits look like a queue for the last door.",
  "petition_writer": "Petition Writer applies polite pressure so persistently that the room notices only after the paperwork becomes a threat.",
  "picket_marshal": "Picket Marshal holds the front like a protected protest route, taunting traffic and cleaning itself up between impacts so the line does not break.",
  "poison_pill_chair": "Poison Pill Chair sits in the front row like a polite governance memo and instantly turns every hostile line into a legal puzzle with teeth.",
  "policy_scribe": "Policy Scribe writes laws no one reads and still gets the last word when enforcement finally arrives.",
  "pollster_pro": "Pollster Pro sells sentiment as a service and packages crowd mood into just enough certainty to move a turn.",
  "prime_broker_brawler": "Prime Broker Brawler settles margin disputes with fists, fees, and the kind of confidence that suggests the collateral was never the point.",
  "probation_hunter": "Probation Hunter tracks dirty repeat offenders like a ledger-backed bounty system with excellent memory.",
  "proxy_lawyer": "Proxy Lawyer weaponizes shareholder votes with such polite wording that the damage lands before the objection is translated.",
  "public_defender": "Public Defender keeps the Wallstreet desk alive with shields, patches the leader between turns, and bills that calm as if serenity were a premium service.",
  "quant_whisperer": "Quant Whisperer backtests your destiny from the back row until the model says attack, then calls the outcome statistically inevitable.",
  "queue_guard_junior": "Queue Guard Junior is a budget depth sponge that blocks more than it costs and learns bad habits from better books.",
  "queue_priority": "Queue Priority front-runs with paperwork and proves clerical speed can still feel like a knife.",
  "quote_blitz": "Quote Blitz spoofs your patience until the lane breaks discipline and hands over the tempo for free.",
  "quote_stacker": "Quote Stacker builds walls of orders so fast the board starts trading around architecture instead of courage.",
  "rebate_harvest": "Rebate Harvest collects maker incentives with farmer discipline and turns tiny returns into a very real turn swing.",
  "reddit_raid_plan": "Reddit Raid Plan looks like a meme brief until the coordinated strike lands and the enemy board realizes the joke had logistics.",
  "rehypothecator": "Rehypothecator turns one share into many owners and acts offended when anyone asks which one gets the original.",
  "research_hawk": "Research Hawk downgrades hope from a safe distance and tags the weakness so the rest of the desk can trade around the bruise.",
  "retail_rebel": "Retail Rebel is the reliable crowd fighter who shows up on curve, trades honestly, and still somehow starts a movement.",
  "risk_examiner": "Risk Examiner checks VaR and vibes in one pass and has bad news for both columns.",
  "risk_modeler": "Risk Modeler speaks fluent Gaussian until reality breaks the curve, then quietly re-labels the damage as a tail event and keeps working.",
  "roadshow_blade": "Roadshow Blade pitches the upside with one hand and opens the lane with the other, which is apparently still legal if the deck looks premium.",
  "roadshow_hype": "Roadshow Hype slides unrealistic TAM across the table so smoothly that by the end of the hearing even the objections sound bullish.",
  "rocket_fuel": "Rocket Fuel adds pure hype pressure with no pretense of subtlety and dares you to call momentum irrational while it is working.",
  "rulebook_slasher": "Rulebook Slasher weaponizes footnotes and proves the appendix can absolutely draw blood.",
  "rumor_forge": "Rumor Forge hammers two damage out of thin confidence and leaves the room arguing over whether the source was ever the point.",
  "settlement_liaison": "Settlement Liaison negotiates in the Judge lane with clearing-house composure and excellent instincts for profitable civility.",
  "shadow_broker": "Shadow Broker skims on contact, bends pressure lanes, and treats Judge-blue access like just another premium line item.",
  "shell_company_maze": "Shell Company Maze siphons shares through a structure so polite and confusing that the theft feels like paperwork.",
  "shell_operator": "Shell Operator runs Mailbox LLC with executive posture and the kind of address book that always points one layer deeper.",
  "short_syndicate_runner": "Short Syndicate Runner is a dirty courier of pressure who moves fast, leaves prints everywhere, and still calls it routine execution.",
  "smirk_veteran": "Smirk Veteran has been wrong for years, remains smug on principle, and somehow keeps turning confidence into pressure value.",
  "spoof_duelist": "Spoof Duelist fights with order-book mirages and wins exchanges by making the opponent swing at liquidity theater.",
  "spread_sniper": "Spread Sniper tags weakness from the back row and leaves exposed targets priced for the rest of the desk to exploit.",
  "spreadsheet_reconciliation": "Spreadsheet Reconciliation stabilizes chaos cell by cell and wins respect the boring way, which is still winning.",
  "staircase_bidder": "Staircase Bidder walks price up one confident step at a time and swears the swagger was never meant to move the whole room.",
  "stonk_charger": "Stonk Charger blasts into the hearing on rocket emojis and backline intent, then pretends the damage was just enthusiastic community engagement.",
  "streaming_analyst": "Streaming Analyst draws rainbow lines, predicts destiny live, and keeps morale high even when the chart is mostly vibes and conviction.",
  "subpoena_rider": "Subpoena Rider delivers papers at melee speed and makes service of process look like a charge attack.",
  "surveillance_marksman": "Surveillance Marksman finds spoofers across the tape and tags them from range with deeply personal accuracy.",
  "swap_architect": "Swap Architect hides exposure in plain sight and drafts risk so elegantly the danger only appears after settlement.",
  "sweep_router": "Sweep Router redirects pressure into hidden liquidity and makes a clean hit look like effortless plumbing.",
  "syndicate_baron": "Syndicate Baron plants in front like it already owns allocation, order flow, and half the apologies that will be issued after close.",
  "synthetic_decoy": "Synthetic Decoy taunts the lane while the real position slips elsewhere, then submits the misdirection as a risk-management success.",
  "synthetic_ledger_keeper": "Synthetic Ledger Keeper adds decimals nobody asked for and still convinces the room the extra precision was necessary.",
  "synthetic_press_release": "Synthetic Press Release pumps the short narrative with polished urgency and just enough plausibility to move the next trade.",
  "tape_listener": "Tape Listener hears every whisper trade and reacts like the market keeps accidentally speaking too loudly.",
  "thread_warrior": "Thread Warrior wins the argument first and the fight second, which is somehow still legal under retail procedure.",
  "tick_mediator": "Tick Mediator brokers one-tick peace treaties that somehow end with better terms for the side who hired it.",
  "ticker_sheriff": "Ticker Sheriff keeps the tape clean-ish, which is still better than most people manage under pressure.",
  "transparency_ledger": "Transparency Ledger stabilizes favor and the public story at once, which is exactly why both sides pretend they wanted it all along.",
  "turnaround_slasher": "Turnaround Slasher cuts costs, cuts corners, and cuts through the line while insisting every ugly hit was disciplined execution.",
  "union_negotiator": "Union Negotiator speaks for the crowd before the Judge with enough backbone to make representation feel like frontline tech.",
  "variance_curator": "Variance Curator sells calm at premium and packages risk tolerance like a luxury product with fine print.",
  "vol_surface_monk": "Vol Surface Monk meditates on skew until the board forgets whether this is enlightenment or positioning.",
  "volatile_knuckle": "Volatile Knuckle throws one-candle madness in a compact package and makes every clean exchange look under-committed.",
  "volatility_clerk": "Volatility Clerk is a stable anchor in noisy tape, filing orderly support while everyone else confuses motion for edge.",
  "volatility_swaplet": "Volatility Swaplet is a pocket-size risk transfer that makes one unit feel smarter for about three very important moments.",
  "whisper_lobbyist": "Whisper Lobbyist reaches through traffic with dirty pressure and sells every suspicious contact as relationship management.",
  "whistleblower_intern": "Whistleblower Intern runs the anonymous tip machine with intern pay and top-tier chaos-per-minute output.",
  "yolo_striker": "YOLO Striker swings on conviction alone and turns \"no thesis\" into a play pattern the opponent keeps underestimating."
};

export function applyCourtCasesToCatalog(cards: CardCatalogV2): CardCatalogV2 {
  return cards.map((card) => {
    if (typeof card.court_case === "string" && card.court_case.trim().length > 0) {
      return card;
    }
    const courtCase = COURT_CASE_BY_CARD_ID[card.id];
    if (typeof courtCase !== "string" || courtCase.trim().length === 0) {
      return card;
    }
    return { ...card, court_case: courtCase };
  });
}
